### ISSUE TITLE
Add GoogleBot UAs

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-device-data#4]
use case:
https://productforums.google.com/forum/#!category-topic/webmasters/mobile/xeViVssd5dQ

https://www.google.com/webmasters/tools/mobile-friendly/ uses those UAs and some UA sniffs treat the bots differently.

Need both Googlebot and Googlebot Mobile UAs.

**Comment by dgozman** [comment]
As I understand, webmasters should not serve different page to the bot. Someone in the thread linked to Cloaking: https://support.google.com/webmasters/answer/66355. If we provide Googlebot UA, it could encourage webmasters to violate the guidelines.

**Comment by Garbee** [comment]
This could go both ways, encourage evil by cloaking or encourage good by making sure you site isn't cloaking.

I think it would be beneficial to include these since we could encourage the use of making sure you are serving the same stuff to Googlebot that you do normal users. This way people can test without needing the knowledge to manually edit (and not mess up) the UA string. Just `Ctrl+Shift+I`, press DM button, select one of the bot entries and refresh. Sounds very reasonable to me.

People that are going to cloak, don't need our help to spoof Googlebot to test with.

**Comment by Garbee** [comment]
Just found that Google even [provides the exact UA strings](https://support.google.com/webmasters/answer/1061943?hl=en) used to crawl different things. I think this could actually be a very beneficial section to add so people can properly test to make sure they are compliant.

**Comment by paulirish** [comment]
Issue moved to https://code.google.com/p/chromium/issues/detail?id=459604 for now.
